@startuml
left to right direction

actor Student
actor Facilitator

rectangle "Student Course Management System" {
  usecase "Create User" as UC1
  usecase "Create Course" as UC2
  usecase "List Courses" as UC3
  usecase "Enroll Student" as UC4
  usecase "View Enrolled Courses" as UC5
  usecase "View Grades" as UC6
  usecase "View Enrolled Students" as UC7
  usecase "Assign Grade" as UC8
}

Student --> UC1
Student --> UC5
Student --> UC6

Facilitator --> UC1
Facilitator --> UC2
Facilitator --> UC3
Facilitator --> UC4
Facilitator --> UC7
Facilitator --> UC8
@enduml
